---
title: "table2_fi"
output: html_document
date: "2024-11-30"
---
load package & data
```{r}
library(dplyr)
library(haven)
library(fixest)

data <- read_dta("~/Desktop/DD_AnalysisDataset_NYR.dta")
dif<- read_dta("~/Desktop/DD_AnalysisDataset_Diffed_NYR.dta")

```

Table2 - (1)

```{r}
data <- data %>%
    select(lozone_max, lozone_8hr, treat_rvpI, treat_rvpII, treat_rfg, treat_CARB,income, DOW, DOY, panelid, region, year, TempMax, TempMin, Rain, Snow)

model1 <- feols(
  lozone_max ~ treat_rvpI + treat_rvpII + treat_rfg + treat_CARB | panelid + region^year,
  data = data
)

summary(model1)

```


Table2 - (2)

```{r}

model2 <- feols(
  lozone_max ~ treat_rvpI + treat_rvpII + treat_rfg + treat_CARB | panelid + region^year + region^DOW + region^DOY + TempMax + TempMin + Rain + Snow,
  data = data
)

summary(model2)

```


Table2 - (3)
```{r}
data$income <- data$income/1000000000

model3 <- feols(
    lozone_max ~ treat_rvpI + treat_rvpII + treat_rfg + treat_CARB + income | panelid + region^year + region^DOW + region^DOY + TempMax + TempMin + Rain + Snow,
    data = data
)

summary(model3)

```

Table2 - (4)

```{r}
dif$incomeD <- dif$incomeD/1000000000

model4 <- feols(
  lozone_maxD ~ 
    treat_rvpID + treat_rvpIID + treat_rfgD  + treat_CARBD + 

    incomeD + 
    
    TrendRVP1D + TrendRVP2D + TrendRVP3D + TrendRVP4D +
    TrendRFG1D + TrendRFG2D + TrendRFG3D + 
    TrendRVPRFG1D + TrendRVPRFG2D + TrendRVPRFG3D + TrendRVPRFG4D +
    TrendCARB4D + TrendCARBRFG4D +
    
    TempMinD + TempMax1D + TempMax2D + TempMax3D +
    TempMin2D + TempMin3D + 
    TempMaxMinD + TempMaxL1D + TempMinL1D +
    TempMaxMaxL1D + TempMaxMinL1D +
    
    RainD + Rain2D + RainTempMaxD +
    SnowD + Snow2D +

    DOYD + DOYTempMax1D + DOYTempMax2D + DOYTempMax3D +
    DOYTempMin1D + DOYTempMin2D + DOYTempMin3D +
    DOYTempMaxMinD + DOYRain1D + DOYRain2D +
    DOYSnow1D + DOYSnow2D + DOYRainTempMaxD +
    DOYTempMaxL1D + DOYTempMinL1D +
    DOYTempMaxMaxL1D + DOYTempMinL1D +
    
    `_DMDOWXTempM_1D` + `_DMDOWXTempM_2D` + `_DMDOWXTempM_3D` +
    `_DMDOWXTempM_4D` + `_DMDOWXTempM_5D` + `_DMDOWXTempM_6D` +
    `_DmDOWXTempM_1D` + `_DmDOWXTempM_2D` + `_DmDOWXTempM_3D` +
    `_DmDOWXTempM_4D` + `_DmDOWXTempM_5D` + `_DmDOWXTempM_6D` +
    
    `_RYyear_1990D` + `_RYyear_1991D` + `_RYyear_1992D` + 
    `_RYyear_1993D` + `_RYyear_1994D` + `_RYyear_1995D` +
    `_RYyear_1996D` + `_RYyear_1997D` + `_RYyear_1998D` +
    `_RYyear_1999D` + `_RYyear_2000D` + `_RYyear_2001D` +
    `_RYyear_2002D` + `_RYyear_2003D` +
    
    `_RWDOWXreg_1_2D` + `_RWDOWXreg_1_3D` + `_RWDOWXreg_1_4D` +
    `_RWDOWXreg_2_2D` + `_RWDOWXreg_2_3D` + `_RWDOWXreg_2_4D`,

  cluster = "A_StateYear",
  data = dif
)

summary(model4)

```


Table2 - (5)

```{r}
model5 <- feols(
  lozone_maxD ~ 
    treat_rvpID + treat_rvpIID + treat_rfgD  + treat_CARBD + 
    
    incomeD + 

    TrendRVP1D + TrendRVP2D + TrendRVP3D + TrendRVP4D +
    TrendRFG1D + TrendRFG2D + TrendRFG3D + 
    TrendRVPRFG1D + TrendRVPRFG2D + TrendRVPRFG3D + TrendRVPRFG4D +
    TrendCARB4D + TrendCARBRFG4D +

    QTrendRVP1D + QTrendRVP2D + QTrendRVP3D + QTrendRVP4D +
    QTrendRFG1D + QTrendRFG2D + QTrendRFG3D +
    QTrendRVPRFG1D + QTrendRVPRFG2D + QTrendRVPRFG3D + QTrendRVPRFG4D +
    QTrendCARB4D +

    TempMinD + TempMax1D + TempMax2D + TempMax3D +
    TempMin2D + TempMin3D + 
    TempMaxMinD + TempMaxL1D + TempMinL1D +
    TempMaxMaxL1D + TempMaxMinL1D +

    RainD + Rain2D + RainTempMaxD +
    SnowD + Snow2D +

    DOYD + DOYTempMax1D + DOYTempMax2D + DOYTempMax3D +
    DOYTempMin1D + DOYTempMin2D + DOYTempMin3D +
    DOYTempMaxMinD + DOYRain1D + DOYRain2D +
    DOYSnow1D + DOYSnow2D + DOYRainTempMaxD +
    DOYTempMaxL1D + DOYTempMinL1D +
    DOYTempMaxMaxL1D + DOYTempMinL1D +

    `_DMDOWXTempM_1D` + `_DMDOWXTempM_2D` + `_DMDOWXTempM_3D` +
    `_DMDOWXTempM_4D` + `_DMDOWXTempM_5D` + `_DMDOWXTempM_6D` +
    `_DmDOWXTempM_1D` + `_DmDOWXTempM_2D` + `_DmDOWXTempM_3D` +
    `_DmDOWXTempM_4D` + `_DmDOWXTempM_5D` + `_DmDOWXTempM_6D` +

    `_RYyear_1990D` + `_RYyear_1991D` + `_RYyear_1992D` + 
    `_RYyear_1993D` + `_RYyear_1994D` + `_RYyear_1995D` +
    `_RYyear_1996D` + `_RYyear_1997D` + `_RYyear_1998D` +
    `_RYyear_1999D` + `_RYyear_2000D` + `_RYyear_2001D` +
    `_RYyear_2002D` + `_RYyear_2003D` +

    `_RWDOWXreg_1_2D` + `_RWDOWXreg_1_3D` + `_RWDOWXreg_1_4D` +
    `_RWDOWXreg_2_2D` + `_RWDOWXreg_2_3D` + `_RWDOWXreg_2_4D`,

  cluster = "A_StateYear",

  data = dif
)

summary(model5)

```
Table2 - (6)

```{r}
model6 <- feols(
  lozone_8hr ~ treat_rvpI + treat_rvpII + treat_rfg + treat_CARB | panelid + region^year,
  data = data
)

summary(model6)

```

Table2 - (7)
```{r}

model7 <- feols(
  lozone_8hr ~ treat_rvpI + treat_rvpII + treat_rfg + treat_CARB | panelid + region^year + region^DOW + region^DOY + TempMax + TempMin + Rain + Snow,
  data = data
)

summary(model7)

```

Table2 - (8)
```{r}
model8 <- feols(
  lozone_8hrD ~ 
    treat_rvpID + treat_rvpIID + treat_rfgD  + treat_CARBD + 
    
    incomeD + 

    TrendRVP1D + TrendRVP2D + TrendRVP3D + TrendRVP4D +
    TrendRFG1D + TrendRFG2D + TrendRFG3D + 
    TrendRVPRFG1D + TrendRVPRFG2D + TrendRVPRFG3D + TrendRVPRFG4D +
    TrendCARB4D + TrendCARBRFG4D +

    QTrendRVP1D + QTrendRVP2D + QTrendRVP3D + QTrendRVP4D +
    QTrendRFG1D + QTrendRFG2D + QTrendRFG3D +
    QTrendRVPRFG1D + QTrendRVPRFG2D + QTrendRVPRFG3D + QTrendRVPRFG4D +
    QTrendCARB4D +

    TempMinD + TempMax1D + TempMax2D + TempMax3D +
    TempMin2D + TempMin3D + 
    TempMaxMinD + TempMaxL1D + TempMinL1D +
    TempMaxMaxL1D + TempMaxMinL1D +

    RainD + Rain2D + RainTempMaxD +
    SnowD + Snow2D +

    DOYD + DOYTempMax1D + DOYTempMax2D + DOYTempMax3D +
    DOYTempMin1D + DOYTempMin2D + DOYTempMin3D +
    DOYTempMaxMinD + DOYRain1D + DOYRain2D +
    DOYSnow1D + DOYSnow2D + DOYRainTempMaxD +
    DOYTempMaxL1D + DOYTempMinL1D +
    DOYTempMaxMaxL1D + DOYTempMinL1D +

    `_DMDOWXTempM_1D` + `_DMDOWXTempM_2D` + `_DMDOWXTempM_3D` +
    `_DMDOWXTempM_4D` + `_DMDOWXTempM_5D` + `_DMDOWXTempM_6D` +
    `_DmDOWXTempM_1D` + `_DmDOWXTempM_2D` + `_DmDOWXTempM_3D` +
    `_DmDOWXTempM_4D` + `_DmDOWXTempM_5D` + `_DmDOWXTempM_6D` +

    `_RYyear_1990D` + `_RYyear_1991D` + `_RYyear_1992D` + 
    `_RYyear_1993D` + `_RYyear_1994D` + `_RYyear_1995D` +
    `_RYyear_1996D` + `_RYyear_1997D` + `_RYyear_1998D` +
    `_RYyear_1999D` + `_RYyear_2000D` + `_RYyear_2001D` +
    `_RYyear_2002D` + `_RYyear_2003D` +

    `_RWDOWXreg_1_2D` + `_RWDOWXreg_1_3D` + `_RWDOWXreg_1_4D` +
    `_RWDOWXreg_2_2D` + `_RWDOWXreg_2_3D` + `_RWDOWXreg_2_4D`,

  cluster = "A_StateYear",

  data = dif
)

summary(model8)

```

Table2 - fi
```{r}
coef_model1 <- coef(model1)
coef_model1["income"] <- NA

coef_model2 <- coef(model2)
coef_model2["income"] <- NA

coef_model3 <- coef(model3)

coef_model6 <- coef(model1)
coef_model6["income"] <- NA

coef_model7 <- coef(model2)
coef_model7["income"] <- NA

selected_vars <- c("treat_rvpID", "treat_rvpIID", "treat_rfgD", "treat_CARBD", "incomeD")

coef_model4 <- sapply(selected_vars, function(var) if (var %in% names(coef(model4))) coef(model4)[var] else NA)
coef_model5 <- sapply(selected_vars, function(var) if (var %in% names(coef(model5))) coef(model5)[var] else NA)
coef_model8 <- sapply(selected_vars, function(var) if (var %in% names(coef(model8))) coef(model8)[var] else NA)


coef_df <- data.frame(
  Model1 = coef_model1,
  Model2 = coef_model2,
  Model3 = coef_model3,
  Model4 = coef_model4,
  Model5 = coef_model5,
  Model6 = coef_model6,
  Model7 = coef_model7,
  Model8 = coef_model8
)

coef_df <- round(coef_df, 3)

print(coef_df)

```



